import React, { useRef } from 'react';

function ReportPrintModal({
  isOpen,
  onClose,
  analytics,
  filters,
  filterMeta,
  user,
}) {
  const printRef = useRef(null);

  if (!isOpen) return null;

  const handlePrint = () => {
    window.print();
  };

  const periodLabelMap = {
    this_month: 'This Month',
    '7d': 'Last 7 Days',
    '30d': 'Last 30 Days',
    quarter: 'This Quarter',
    year: 'This Year',
    all: 'All Time',
  };

  const selectedPeriodLabel = periodLabelMap[filters?.period] || 'This Month';
  const selectedRepName = filterMeta?.sales_reps?.find((r) => String(r.id) === String(filters?.sales_rep_id))?.name || 'All Representatives';
  const currentDateStr = new Date().toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  const summary = analytics?.summaryKpis || {};
  const bottlenecks = analytics?.approvalBottlenecks || {};
  const topProducts = analytics?.topProducts || [];
  const revenueMix = analytics?.revenueMix || {};
  const salesTrends = analytics?.salesTrends || [];
  const leaderboard = analytics?.salesRepLeaderboard || [];

  const recurring = parseFloat(revenueMix?.recurring_revenue || 0);
  const onetime = parseFloat(revenueMix?.onetime_revenue || 0);
  const totalRev = recurring + onetime;
  const recurringPct = totalRev > 0 ? Math.round((recurring / totalRev) * 100) : 0;
  const onetimePct = totalRev > 0 ? 100 - recurringPct : 0;

  const totalRequested = Number(bottlenecks?.total_approvals_requested || 0);
  const avgApprovalHours = totalRequested > 0 ? Number(bottlenecks?.avg_approval_hours || 0) : 0;
  const managerHours = totalRequested > 0 ? Number(bottlenecks?.manager_avg_hours || 0) : 0;
  const financeHours = totalRequested > 0 ? Number(bottlenecks?.finance_avg_hours || 0) : 0;

  return (
    <div className="df-reports-print-modal-backdrop" onClick={onClose}>
      <div className="df-reports-print-modal" onClick={(e) => e.stopPropagation()}>
        {/* Top Control Bar */}
        <div className="df-reports-print-modal__bar">
          <div className="df-reports-print-modal__bar-title">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" width="20" height="20">
              <polyline points="6 9 6 2 18 2 18 9" />
              <path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2" />
              <rect x="6" y="14" width="12" height="8" />
            </svg>
            Executive Analytics PDF Document Preview
          </div>
          <div className="df-reports-print-modal__bar-actions">
            <button
              type="button"
              className="df-reports-print-modal__btn df-reports-print-modal__btn--print"
              onClick={handlePrint}
            >
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" width="16" height="16">
                <polyline points="6 9 6 2 18 2 18 9" />
                <path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2" />
                <rect x="6" y="14" width="12" height="8" />
              </svg>
              Print / Save as PDF
            </button>
            <button
              type="button"
              className="df-reports-print-modal__btn df-reports-print-modal__btn--close"
              onClick={onClose}
            >
              ✕ Close
            </button>
          </div>
        </div>

        {/* Printable Executive Document Sheet */}
        <div className="df-reports-print-doc" ref={printRef} id="printable-executive-report">
          {/* Document Header */}
          <div className="df-reports-print-doc__header">
            <div className="df-reports-print-doc__header-brand">
              <div className="df-reports-print-doc__brand-badge">DealFlow360</div>
              <div className="df-reports-print-doc__brand-sub">Enterprise Sales Operations & Revenue Platform</div>
            </div>
            <div className="df-reports-print-doc__header-meta">
              <div className="meta-title">Executive Performance Report</div>
              <div className="meta-row"><strong>Period:</strong> {selectedPeriodLabel}</div>
              <div className="meta-row"><strong>Generated:</strong> {currentDateStr}</div>
              <div className="meta-row"><strong>Sales Team:</strong> {selectedRepName}</div>
              <div className="meta-row"><strong>Generated By:</strong> {user?.name || 'Administrator'}</div>
            </div>
          </div>

          <hr className="df-reports-print-doc__divider" />

          {/* Section 1: Executive KPI Scorecard */}
          <div className="df-reports-print-doc__section">
            <h2 className="df-reports-print-doc__section-title">1. Executive Summary Scorecard</h2>
            <div className="df-reports-print-doc__kpi-grid">
              <div className="df-reports-print-doc__kpi-box">
                <div className="kpi-lbl">Quotes Created</div>
                <div className="kpi-val">{summary.quotes_created_count || 0}</div>
                <div className="kpi-sub">Total deal opportunities</div>
              </div>
              <div className="df-reports-print-doc__kpi-box">
                <div className="kpi-lbl">Total Pipeline Value</div>
                <div className="kpi-val">₹{Number(summary.total_pipeline_value || 0).toLocaleString('en-IN')}</div>
                <div className="kpi-sub">Total proposed quotation sum</div>
              </div>
              <div className="df-reports-print-doc__kpi-box">
                <div className="kpi-lbl">Confirmed Revenue</div>
                <div className="kpi-val">₹{Number(summary.confirmed_revenue_value || 0).toLocaleString('en-IN')}</div>
                <div className="kpi-sub">{summary.confirmed_deals_count || 0} closed deals</div>
              </div>
              <div className="df-reports-print-doc__kpi-box">
                <div className="kpi-lbl">Win / Realization Rate</div>
                <div className="kpi-val">{summary.win_rate_percentage || 0}%</div>
                <div className="kpi-sub">Proposal to contract conversion</div>
              </div>
              <div className="df-reports-print-doc__kpi-box">
                <div className="kpi-lbl">Average Turnaround</div>
                <div className="kpi-val">{avgApprovalHours} hrs</div>
                <div className="kpi-sub">Request to approval time</div>
              </div>
              <div className="df-reports-print-doc__kpi-box">
                <div className="kpi-lbl">Average Discount</div>
                <div className="kpi-val">{summary.avg_discount_percentage || 0}%</div>
                <div className="kpi-sub">Margin compliance indicator</div>
              </div>
            </div>
          </div>

          {/* Section 2: Approval Performance & Turnaround Metrics */}
          <div className="df-reports-print-doc__section">
            <h2 className="df-reports-print-doc__section-title">2. Approval Bottlenecks & Turnaround Times</h2>
            <table className="df-reports-print-doc__table">
              <thead>
                <tr>
                  <th>Approval Stage / Metric</th>
                  <th>Duration / Value</th>
                  <th>Benchmark / SLA</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Sales Manager Review Duration</td>
                  <td><strong>{managerHours} hours</strong></td>
                  <td>&lt; 4.0 hours</td>
                  <td><span className="doc-badge doc-badge--green">On Track</span></td>
                </tr>
                <tr>
                  <td>Finance Review Duration (High Risk Deals)</td>
                  <td><strong>{financeHours} hours</strong></td>
                  <td>&lt; 8.0 hours</td>
                  <td><span className="doc-badge doc-badge--green">On Track</span></td>
                </tr>
                <tr>
                  <td>Overall Workflow Turnaround</td>
                  <td><strong>{avgApprovalHours} hours</strong></td>
                  <td>&lt; 12.0 hours</td>
                  <td><span className="doc-badge doc-badge--green">Compliant</span></td>
                </tr>
                <tr>
                  <td>Approval Pass Rate</td>
                  <td><strong>{bottlenecks.approval_rate_pct || 0}%</strong></td>
                  <td>&gt; 70.0%</td>
                  <td><span className="doc-badge doc-badge--blue">{bottlenecks.total_approved_count || 0} Approved</span></td>
                </tr>
                <tr>
                  <td>Total Workflow Requests Processed</td>
                  <td><strong>{bottlenecks.total_approvals_requested || 0}</strong></td>
                  <td>-</td>
                  <td>{bottlenecks.total_rejected_count || 0} Rejected / {bottlenecks.total_returned_count || 0} Returned</td>
                </tr>
              </tbody>
            </table>
          </div>

          {/* Section 3: Revenue Distribution Mix */}
          <div className="df-reports-print-doc__section">
            <h2 className="df-reports-print-doc__section-title">3. Revenue Realization & Product Mix</h2>
            <div className="df-reports-print-doc__mix-boxes">
              <div className="mix-card">
                <div className="mix-type">One-Time Hardware / Products</div>
                <div className="mix-amt">₹{Number(onetime).toLocaleString('en-IN')}</div>
                <div className="mix-pct">{onetimePct}% of total realization</div>
              </div>
              <div className="mix-card">
                <div className="mix-type">Recurring Subscriptions & AMC</div>
                <div className="mix-amt">₹{Number(recurring).toLocaleString('en-IN')}</div>
                <div className="mix-pct">{recurringPct}% of total realization</div>
              </div>
            </div>
          </div>

          {/* Section 4: Top Product Performance & Upsell Attach Rates */}
          <div className="df-reports-print-doc__section">
            <h2 className="df-reports-print-doc__section-title">4. Top Product Sales & Upsell Attach Performance</h2>
            <table className="df-reports-print-doc__table">
              <thead>
                <tr>
                  <th>Product Name</th>
                  <th>SKU</th>
                  <th>Category</th>
                  <th>Units Sold</th>
                  <th>Total Revenue</th>
                  <th>Upsell Attach Rate</th>
                </tr>
              </thead>
              <tbody>
                {topProducts.map((p, idx) => (
                  <tr key={idx}>
                    <td><strong>{p.product_name}</strong></td>
                    <td>{p.sku || 'N/A'}</td>
                    <td>{p.category_name}</td>
                    <td>{p.units_sold}</td>
                    <td>₹{Number(p.total_revenue || 0).toLocaleString('en-IN')}</td>
                    <td>
                      <strong>{p.upsell_attach_rate_pct}%</strong> ({p.upsell_count || 0} attach units)
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Section 5: Sales Representative Leaderboard */}
          <div className="df-reports-print-doc__section">
            <h2 className="df-reports-print-doc__section-title">5. Sales Representative Leaderboard & Margin Compliance</h2>
            <table className="df-reports-print-doc__table">
              <thead>
                <tr>
                  <th>Rank</th>
                  <th>Representative</th>
                  <th>Quotes Created</th>
                  <th>Deals Closed</th>
                  <th>Total Revenue Realized</th>
                  <th>Win Rate</th>
                  <th>Avg Discount</th>
                </tr>
              </thead>
              <tbody>
                {leaderboard.map((rep, idx) => (
                  <tr key={idx}>
                    <td>#{idx + 1}</td>
                    <td><strong>{rep.rep_name}</strong> ({rep.rep_email})</td>
                    <td>{rep.total_quotes}</td>
                    <td>{rep.deals_closed}</td>
                    <td><strong>₹{Number(rep.total_revenue || 0).toLocaleString('en-IN')}</strong></td>
                    <td>{rep.win_rate_pct}%</td>
                    <td>{rep.avg_discount_pct}%</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Document Footer with Sign-off */}
          <div className="df-reports-print-doc__footer">
            <div className="footer-notes">
              <p>
                <strong>CONFIDENTIAL DOCUMENT:</strong> This report is generated automatically by DealFlow360 for executive review and audit purposes.
              </p>
            </div>
            <div className="footer-signoff">
              <div className="sign-box">
                <div className="sign-line" />
                <div className="sign-lbl">Sales Director / VP Signature</div>
              </div>
              <div className="sign-box">
                <div className="sign-line" />
                <div className="sign-lbl">Finance Controller Signature</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default React.memo(ReportPrintModal);
