/**
 * DealFlow360 Canonical Roles and Permission Matrix
 * Based on Section 3 & 4 of DealFlow360 Specification
 */

export const ROLES = {
  ADMIN: 'admin',
  SALES_REP: 'sales_rep',
  SALES_MANAGER: 'sales_manager',
  FINANCE: 'finance',
  OPERATIONS: 'operations',
  CUSTOMER: 'customer',
};

export const ALL_INTERNAL_ROLES = [
  ROLES.ADMIN,
  ROLES.SALES_REP,
  ROLES.SALES_MANAGER,
  ROLES.FINANCE,
  ROLES.OPERATIONS,
];

export const PERMISSIONS = {
  // Quotations & Negotiations
  QUOTATION_BUILD: [ROLES.ADMIN, ROLES.SALES_REP, ROLES.SALES_MANAGER],
  QUOTATION_VIEW_ALL: [ROLES.ADMIN, ROLES.SALES_MANAGER, ROLES.FINANCE],
  QUOTATION_NEGOTIATE_INTERNAL: [ROLES.ADMIN, ROLES.SALES_REP, ROLES.SALES_MANAGER],
  QUOTATION_NEGOTIATE_PORTAL: [ROLES.CUSTOMER],

  // Approvals
  APPROVAL_REVIEW_MANAGER: [ROLES.ADMIN, ROLES.SALES_MANAGER],
  APPROVAL_REVIEW_FINANCE: [ROLES.ADMIN, ROLES.FINANCE],
  APPROVAL_VIEW_QUEUE: [ROLES.ADMIN, ROLES.SALES_MANAGER, ROLES.FINANCE],

  // Discount Governance
  DISCOUNT_RULES_CONFIGURE: [ROLES.ADMIN, ROLES.SALES_MANAGER],

  // Fulfillment & Multi-Warehouse
  FULFILLMENT_VIEW: [ROLES.ADMIN, ROLES.OPERATIONS, ROLES.FINANCE, ROLES.SALES_MANAGER, ROLES.SALES_REP],
  FULFILLMENT_MANAGE_SPLIT: [ROLES.ADMIN, ROLES.OPERATIONS, ROLES.FINANCE],
  WAREHOUSE_STOCK_MANAGE: [ROLES.ADMIN, ROLES.OPERATIONS],

  // Billing, Invoices & Subscriptions
  INVOICE_CREATE: [ROLES.ADMIN, ROLES.FINANCE],
  INVOICE_RECORD_PAYMENT: [ROLES.ADMIN, ROLES.FINANCE],
  SUBSCRIPTION_MANAGE: [ROLES.ADMIN, ROLES.FINANCE],
  SUBSCRIPTION_CANCEL_CREDIT: [ROLES.ADMIN, ROLES.FINANCE],

  // Deal Health & Anomaly Management
  DEAL_HEALTH_VIEW: [ROLES.ADMIN, ROLES.SALES_MANAGER, ROLES.FINANCE, ROLES.SALES_REP],
  DEAL_HEALTH_CONFIGURE: [ROLES.ADMIN, ROLES.SALES_MANAGER],
  DEAL_HEALTH_TRIGGER_ACTION: [ROLES.ADMIN, ROLES.SALES_MANAGER, ROLES.FINANCE],

  // Reports & Analytics
  REPORTS_VIEW: [ROLES.ADMIN, ROLES.SALES_MANAGER, ROLES.FINANCE, ROLES.OPERATIONS, ROLES.SALES_REP],
  REPORTS_EXPORT_PDF: [ROLES.ADMIN, ROLES.SALES_MANAGER, ROLES.FINANCE, ROLES.OPERATIONS, ROLES.SALES_REP],

  // Product Catalog
  CATALOG_MANAGE: [ROLES.ADMIN, ROLES.SALES_MANAGER, ROLES.OPERATIONS],

  // Staff & System Setup
  STAFF_MANAGE: [ROLES.ADMIN],
};

/**
 * Checks if a given role has the specified permission
 * @param {string} role 
 * @param {string} permissionKey 
 * @returns {boolean}
 */
export const hasPermission = (role, permissionKey) => {
  if (!role) return false;
  if (role === ROLES.ADMIN) return true; // Superuser bypass
  const allowed = PERMISSIONS[permissionKey];
  return Array.isArray(allowed) && allowed.includes(role);
};
